/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1d",
        "primary-fixed-dim": "#00dce6",
        "primary": "#e3fdff",
        "tertiary": "#e8ffda",
        "secondary": "#ffabf3",
        "error": "#ffb4ab",
        "surface-container-highest": "#353437",
        "inverse-on-surface": "#313032",
        "tertiary-fixed-dim": "#2ae500",
        "on-surface-variant": "#b9cacb",
        "secondary-fixed-dim": "#ffabf3",
        "outline-variant": "#3a494b",
        "secondary-container": "#fe00fe",
        "surface": "#131315",
        "outline": "#849495",
        "inverse-primary": "#00696f",
        "secondary-fixed": "#ffd7f5",
        "surface-tint": "#00dce6",
        "primary-container": "#00f3ff",
        "inverse-surface": "#e5e1e4",
        "surface-container-high": "#2a2a2c",
        "surface-container-lowest": "#0e0e10",
        "surface-container": "#201f21",
        "background": "#131315",
        "primary-fixed": "#6ff6ff",
        "tertiary-fixed": "#79ff5b",
        "on-primary": "#00373a",
        "on-surface": "#e5e1e4",
        "on-error": "#690005",
        "on-secondary": "#5b005b",
        "error-container": "#93000a",
        "on-background": "#e5e1e4",
        "surface-variant": "#353437",
        "surface-dim": "#131315",
        "tactical-black": "#050505",
        "cyber-cyan": "#00f3ff",
        "elec-yellow": "#fcee0a",
        "crimson-red": "#ff003c"
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"], 
        "headline-md": ["Space Grotesk", "sans-serif"], 
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"], 
        "label-caps": ["JetBrains Mono", "monospace"], 
        "display": ["Pixelify Sans", "sans-serif"],
        "code": ["VT323", "monospace"], 
        "body-md": ["Pixelify Sans", "monospace"], 
        "terminal": ["VT323", "monospace"],
        "pixel": ["Pixelify Sans", "monospace"]
      }
    },
  },
  plugins: [],
}
