import { BriefcaseBusiness, Code2 } from 'lucide-react';

const experience = [
  { period: '2026 — Present', role: 'Backend Engineer Intern', company: 'Digitak Labs', icon: Code2, description: 'Building backend systems for a food delivery application, from API development and database design to GitLab-based delivery workflows.', points: ['API and backend feature development', 'Relational database design', 'CI/CD workflow management'], tags: ['Backend', 'API', 'GitLab CI/CD'] },
  { period: 'May 2026', role: 'Development Team', company: 'SI MANTAP', icon: BriefcaseBusiness, description: 'Contributed student guidance features to a production university management application.', points: ['Production feature delivery', 'Team-based implementation', 'Quality-focused iteration'], tags: ['Development', 'Production', 'Collaboration'] },
];

export default function Timeline() {
  return <div><header className="max-w-5xl pb-20 pt-8"><p className="font-code text-[10px] uppercase tracking-[.22em] text-resonance">03 / Field history</p><h1 className="mt-6 text-5xl font-semibold leading-[.95] tracking-[-.05em] text-white md:text-8xl">Experience,<br />without the noise.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted">A concise record of the systems, teams, and responsibilities shaping my engineering practice.</p></header>
    <section className="relative ml-3 border-l border-white/10 pb-12 md:ml-24">{experience.map((item, index) => <article key={item.company} className="relative grid gap-7 pb-20 pl-9 md:grid-cols-12 md:pl-16"><span className="absolute -left-[5px] top-2 h-[9px] w-[9px] rotate-45 bg-resonance shadow-[0_0_18px_rgba(121,230,223,.6)]" /><div className="md:col-span-3"><span className="font-code text-[10px] uppercase tracking-[.18em] text-resonance">{item.period}</span><p className="mt-3 text-sm text-muted">Signal log 0{index + 1}</p></div><div className="md:col-span-9"><item.icon size={22} className="mb-5 text-acid" /><h2 className="text-3xl font-medium tracking-[-.03em] text-white md:text-5xl">{item.role}</h2><p className="mt-2 font-code text-xs uppercase tracking-[.15em] text-muted">{item.company}</p><p className="mt-6 max-w-2xl leading-7 text-muted">{item.description}</p><ul className="mt-6 space-y-3">{item.points.map(point => <li key={point} className="flex gap-3 text-sm text-white/80"><span className="text-resonance">↳</span>{point}</li>)}</ul><div className="mt-7 flex flex-wrap gap-2">{item.tags.map(tag => <span key={tag} className="tech-tag">{tag}</span>)}</div></div></article>)}</section>
  </div>;
}
